change upgrade test versions to v1.4.3 in v1.5.x pipeline
longhorn/infra pull request #133
Opened 2023-07-21 01:27 UTC by chriscchien

change upgrade test versions to v1.4.3 in v1.5.x pipeline

2023-07-21 03:17 UTC, yangchiu commented
Besides `v1.4.3 to v1.5.x`, should we also test `v1.5.1 to v1.5.x` too? cc @innobead

2023-07-27 06:16 UTC, innobead commented
> Besides `v1.4.3 to v1.5.x`, should we also test `v1.5.1 to v1.5.x` too? cc @innobead

Yes, as discussed, we should just do the same as v1.4.x pipelines.

[/jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml#L128-L132](https://github.com/longhorn/infra/blob/be5b4eec059b7e3a180197b1dbe7a7e5f70a8d6f/jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml#L128-L132)
```yml
      - parameterized-timer:
          cron: |
            TZ=Asia/Taipei
            H 19 * * 0,1,3,5 % BACKUP_STORE_TYPE=s3;LONGHORN_STABLE_VERSION=v1.4.2
            H 19 * * 2,4,6 % BACKUP_STORE_TYPE=nfs;LONGHORN_STABLE_VERSION=v1.3.3
```

cc @longhorn/qa

2023-07-27 06:16 UTC, innobead requested changes
@chriscchien Please update the PR as per the review.

2023-07-27 06:45 UTC, innobead commented
Again, leave @yangchiu to manage all PRs here if they have been reviewed. 

cc @longhorn/qa

2023-07-27 06:49 UTC, innobead requested changes

2023-07-27 06:49 UTC, innobead commented on jenkins-jobs/v1.5.x/longhorn-upgrade-tests-sles-arm64.yml
> +          default: "v1.4.3"
This should be changed to 1.5.1, the latest patch 1.5, since this pipeline is for 1.5.

2023-08-02 00:27 UTC, yangchiu approved these changes
LGTM

2023-08-02 00:28 UTC, merged