change upgrade test versions to v1.4.3 in v1.4.x pipeline
longhorn/infra pull request #134
Opened 2023-07-21 01:30 UTC by chriscchien

Follow code pattern, change upgrade test versions from v1.4.2 to v1.4.3 in v1.4.x pipeline

2023-07-21 03:14 UTC, yangchiu approved these changes
LGTM

2023-07-27 06:19 UTC, yangchiu requested changes
This part needs to update too:
https://github.com/longhorn/infra/blob/be5b4eec059b7e3a180197b1dbe7a7e5f70a8d6f/jenkins-jobs/v1.4.x/longhorn-upgrade-tests-sles-amd64.yml#L128-L132

2023-07-27 06:46 UTC, innobead approved these changes

2023-08-02 00:30 UTC, yangchiu approved these changes
LGTM

2023-08-02 00:30 UTC, merged