Update the regression job parameters to the new versions of k3s and R…
longhorn/infra pull request #149
Opened 2023-11-23 03:12 UTC by roger-ryao

…ke2, and set a stable Longhorn version.

ref. longhorn/longhorn#7035

2023-11-23 13:35 UTC, innobead requested changes
We don't need to update the current supported branches (1.5 and 1.4); instead, let's just update the master.

The rule is below.
- For supported branches, no need to update K8s distro. However, ensure the version of SLE micro and SLE up-to-date.
- Only need to update the distro version of the master branch to the last K8s feature (major/minor) version. (K8s has 3 month release cadence)
- Always keep the version of SLES and SLE Micro up-to-date in all branches. Currently, sles is 15.5 and sle micro 5.5.

2023-11-23 13:35 UTC, innobead commented on jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
> +          default: "v1.27.7+k3s1"
Why using a different version instead of ` "v1.28.3+k3s1"`?

2023-11-24 00:56 UTC, roger-ryao commented
> * Keep the other distro versions up-to-date on the master branches. Currently, SLE is 15.5 and SLE micro 5.5.

Regarding sle-micro, I haven't run it on `5.5` yet. This requires additional time for verification.

2023-11-24 00:57 UTC, roger-ryao commented on jenkins-jobs/master/oracle/longhorn-upgrade-tests-oracle-amd64.yml
> +          default: "v1.27.7+k3s1"
> Why using a different version instead of ` "v1.28.3+k3s1"`?

For our regression testing with Longhorn `1.5.3`, we use k3s version `1.27`. Therefore, I chose to use `1.27` for the upgrade test cases instead of `1.28`. This enables us to run `master-head` regression tests on both k3s `1.27` and `1.28` concurrently. If you think it's necessary to keep `master-head` consistent, I'll adjust my PR.

2023-12-08 03:29 UTC, roger-ryao commented
> > * Keep the other distro versions up-to-date on the master branches. Currently, SLE is 15.5 and SLE micro 5.5.
> 
> Regarding sle-micro, I haven't run it on `5.5` yet. This requires additional time for verification.

https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/amd64/job/longhorn-tests-sle-micro-amd64/130/ : 3 failed cases
https://ci.longhorn.io/job/public/job/master/job/sle-micro/job/arm64/job/longhorn-tests-sle-micro-arm64/26/ : 4 failed cases

The 2 failed cases [test_disk_eviction_with_node_level_soft_anti_affinity_disabled](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-2-stage-upgrade-tests-sles-arm64/367/testReport/junit/tests/test_node/test_disk_eviction_with_node_level_soft_anti_affinity_disabled/) are due to [issue-7210](https://github.com/longhorn/longhorn/issues/7210).
We have created the [PR-1607](https://github.com/longhorn/longhorn-tests/pull/1607) to fix that.

2023-12-08 11:09 UTC, c3y1huang commented on jenkins-jobs/longhorn-tests-regression.yml
> +          default: "v1.28.3+k3s1"
Heads up, [v1.28.4+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.28.4%2Bk3s1) is out.

2023-12-08 13:11 UTC, innobead commented on jenkins-jobs/longhorn-tests-regression.yml
> +          default: "v1.28.3+k3s1"
Roger, just update but no need to retest this again.

2023-12-20 06:14 UTC, innobead approved these changes
LGTM.

2023-12-20 06:14 UTC, merged