extend nightly tests OS support matrix
longhorn/infra pull request #68
Opened 2021-11-12 20:16 UTC by meldafrawi

https://github.com/longhorn/longhorn/issues/3085
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

2021-11-12 22:01 UTC, khushboo-rancher commented on jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-amd64.yml
> +      - parameterized-timer:
Same as above comment.

2021-11-13 03:02 UTC, innobead commented on jenkins-jobs/master/centos/longhorn-tests-centos-amd64.yml
> +    triggers:
We don’t need to run daily but on demand instead.

2021-11-15 06:29 UTC, innobead requested changes
Let's just keep SLES running every day, but others on demand.

P.S. we will also change our nightly build based on SLES instead of Ubuntu.

2021-11-15 22:10 UTC, meldafrawi commented on jenkins-jobs/master/centos/longhorn-tests-centos-amd64.yml
> +    triggers:
fixed, Thanks.

2021-11-15 22:11 UTC, meldafrawi commented on jenkins-jobs/master/centos/longhorn-upgrade-tests-centos-amd64.yml
> +      - parameterized-timer:
fixed, Thanks.

2021-11-15 22:12 UTC, meldafrawi commented
I'll address changing default distro to SLES in another separate PR.

2021-11-15 22:39 UTC, innobead approved these changes

2021-11-15 22:39 UTC, merged